### ISSUE TITLE
Changing the then-method key

### ISSUE THREAD

**Issue by MichaelTheriot** [devsnek/proposal-symbol-thenable#1]
I think there should be a way to configure the key Promise.resolve tries to use for the then-method, instead of simply opting out. Then you could instruct Promise.resolve to check another property and still use 'then' for whatever purpose.

**Comment by devsnek** [comment]
if you're not using the literal string "then" there's no reason for the behaviour to exist in the first place. It's called a "thenable."

**Comment by MichaelTheriot** [comment]
> if you're not using the literal string "then" there's no reason for the behaviour to exist in the first place. It's literally called a "thenable."
> 
Consider the made up scenario:

(async function () {

  let delay = {now: 5000, then: 10000, wait: function (resolve) { setTimeout(resolve, this.then - this.now); }};
  await delay;
  console.log('done');

})();

vs

(async function () {

  let delay = {now: 5000, then2: 10000, then: function (resolve) { setTimeout(resolve, this.then2 - this.now); }};
  await delay;
  console.log('done');

})();


One prints "done" immediately while the other waits 5 seconds, simply because of a language decision on what key to use as the promise generator. Hence I believe a proposal to modify how Promise.resolve behaves should also include a way to modify this behavior.

**Comment by devsnek** [comment]
right and I'm saying the goal here is to reduce spaghetti like that, not encourage new ways to make it less apparent what the spaghetti is doing. if you want to make a delay function just be explicit and use the promise constructor.

**Comment by MichaelTheriot** [comment]
O.K. then, I did not gather this from your readme. I'd argue adding symbolic properties to modify standard behavior is only contributing to making things less apparent.

**Comment by devsnek** [comment]
@MichaelTheriot i generally agree with that but it seems like its still the best option at the moment
