### ISSUE TITLE
Pros/cons of symbol on object with then method vs on method

### ISSUE THREAD

**Issue by mikesamuel** [devsnek/proposal-symbol-thenable#3]
It seems that opting out of being treated as thenable is mostly necessary when the presence of the `then` method is coincidental -- there is a method named `then` but its purpose is not related to promise resolution.

If that's the case, then the opt-out is necessary because of something about the `then` method, not something about the object.

Maybe document why/whether adding a marker symbol to the object is preferable to adding a marker symbol to the `then` method.

**Comment by devsnek** [comment]
to make sure i understand you, like why put the symbol on the object holding the then instead of like `obj.then[Symbol.ignoreMePls] = true`?

**Comment by mikesamuel** [comment]
Yes

**Comment by devsnek** [comment]
it's fewer gets/checks I suppose. I assume engines can optimise that away but on the object seems simplest, do you have an argument for the other?

**Comment by ljharb** [comment]
How would that work with an object where the then method is inherited, but only the actual object (not all its siblings) should be non-thenable?

**Comment by ljharb** [comment]
(With the symbol on the object, you don’t even have to check the “then” method, potentially)

**Comment by devsnek** [comment]
it also would make keeping our language stuff (like namespaces) unthenable much harder

**Comment by devsnek** [comment]
seems like this has been addressed, feel free to re-open otherwise
