### ISSUE TITLE
How to use this with thenable objects?

### ISSUE THREAD

**Issue by piranna** [devsnek/proposal-symbol-thenable#8]
The example talks about a `.then()` method that return a Date instead of a Promise, but how could I do the same when it return a Promise, but don't want to consider it a thenable object?

A real life example (a pitfall I've fallen several times) is when I construct an object that would last some time until it's ready or can fail (for example a network connection) so I add a `.then()` method on the class resolving to the object itself when it's ready to be used. Problem is, since I'm resolving to a thenable object (the object itself), the `.then()` method is called again, and I end up in an infinite loop.

```js
class A {
  then(onResolve){
    onResolve(this)
  }
}

new A().then(function(instance){
  // never called
})
```

Only solution I've found is to remove the `then()` method once it's resolved, or don't return the `this` instance. How could this be fixed? Setting the symbol would not prevent to be used as a thenable anymore? Maybe an `isNotThenable` flag could be added to `Promise.resolve()` to don't check if the resolved value is a thenable object? This way `onResolve` would be set to the promise returned by `Promise.resolve()`, that resolve to a non-thenable object:

```js
class A {
  then(onResolve){
    onResolve(Promise.resolve(this, true))
  }
}

new A().then(function(instance){
  instance.constructor === A  // true

  return instance.then(function(){
    // this should still work since `then` is called directly
    return 'blah'
  })
})
.then(console.log)  // 'blah'
```

**Comment by ljharb** [comment]
This proposal wouldn't be able to address your need to have an object both be thenable and not at the same time. However, you could do:
```js
class A {
  then(onResolve){
    this[Symbol.thenable] = false;
    onResolve(this);
  }
}
```
which would make it non-thenable afterwards?

**Comment by piranna** [comment]
That could do the job. Would the `.then()` method still work if called explicitly (`instance.then()`)?

**Comment by ljharb** [comment]
Yes, since only the Promise implementation would check the symbol.

**Comment by piranna** [comment]
> Yes, since only the Promise implementation would check the symbol.

Perfect, then I think it will do the job ;-) Thank you! :-D Do you think it can be an example use case? Or is it too much corner case? :-)

**Comment by devsnek** [comment]
i think a better pattern to fall into would be
```js
class A {
  connect(){
    return somePromise;
  }
}

const a = new A();
a.connect().then(() => { /* do something with a */ });
```

**Comment by piranna** [comment]
Yeah, but this would only work on APIs where a valid state is disconnected and user can connect and disconnect at (mostly) any time. For APIs that hidden the connection process, it will not work.
