### ISSUE TITLE
Alternative Proposal: Extend `import` syntax to allow boxing of the module

### ISSUE THREAD

**Issue by Jamesernator** [devsnek/proposal-symbol-thenable#9]
While `Symbol.thenable` might be more widely useful than just solving the case of `import()` for the most part the `.then`-able issue can be solved by wrapping the promise in a trivial object e.g.: `{ value: somePromise }`.

This can't be done for `import()` (generally even if `data:` URLs might work in the browser) as the Promise is always created by the host. So I'd propose that a mechanism directly for `import()` is created that performs this boxing.

I suggested a few mechanisms back in the [original issue](https://github.com/tc39/proposal-dynamic-import/issues/47#issuecomment-322081432) about dynamic import thenables which could be used for solving this particular case.

**Comment by ljharb** [comment]
The champion for `import()` was staunchly against any mechanism to address this that didn't apply to all promises everywhere, so I'm afraid that's a nonstarter (further down that very thread).

**Comment by Jamesernator** [comment]
I re-raised this because I read the [meeting notes](https://tc39.github.io/tc39-notes/2018-05_may-24.html#symbolthenable-for-stage-1-or-2) as it seems like people were opposed to changing the status quo for modules and generally weren't favourable to `Symbol.thenable`.

So I don't really see how we can have both the capability to get the original module object without either fixing it on modules or fixing it on `import()` both of which seem unpopular based on what I read in those notes and the original issue.

**Comment by ljharb** [comment]
The current status is that we can’t get either, unless I’m able to come back to the committee with a different suggestion.
